---
apiVersion: v1
kind: Service
metadata:
  name: artgallery
  namespace: challenges
  annotations:
    cloud.google.com/backend-config: '{"default": "release-wave-2"}'
spec:
  selector:
    app: artgallery
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artgallery
  labels:
    app: artgallery
  namespace: challenges
spec:
  selector:
    matchLabels:
      app: artgallery
  replicas: 2
  template:
    metadata:
      labels:
        app: artgallery
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: In
                    values:
                      - maplectf-node-pool
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: artgallery
          image: gcr.io/maplectf-2022/artgallery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: artgallery
#  namespace: challenges
#spec:
#  rules:
#    - host: artgallery.ctf.maplebacon.org
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: artgallery
#                port:
#                  number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: artgallery
  namespace: challenges
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: artgallery
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
