---
apiVersion: v1
kind: Service
metadata:
  name: jwt
  namespace: challenges
  annotations:
    cloud.google.com/backend-config: '{"default": "jwt-healthcheck"}'
spec:
  selector:
    app: jwt
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt
  labels:
    app: jwt
  namespace: challenges
spec:
  selector:
    matchLabels:
      app: jwt
  replicas: 2
  template:
    metadata:
      labels:
        app: jwt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: In
                    values:
                      - maplectf-node-pool
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: jwt
          image: gcr.io/maplectf-2022/jwt:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jwt
  namespace: challenges
spec:
  rules:
    - host: jwt.ctf.maplebacon.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jwt
                port:
                  number: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: jwt-healthcheck
  namespace: challenges
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8000
    type: HTTP
    requestPath: /health
  securityPolicy:
    name: ""
  sessionAffinity:
    affinityType: "CLIENT_IP"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jwt
  namespace: challenges
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jwt
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
