---
apiVersion: v1
kind: Service
metadata:
  name: maplebacoin
  namespace: challenges
  annotations:
    cloud.google.com/backend-config: '{"default": "release-wave-2"}'
spec:
  selector:
    app: maplebacoin
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maplebacoin
  labels:
    app: maplebacoin
  namespace: challenges
spec:
  selector:
    matchLabels:
      app: maplebacoin
  replicas: 3
  template:
    metadata:
      labels:
        app: maplebacoin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: In
                    values:
                      - maplectf-node-pool
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: maplebacoin
          image: gcr.io/maplectf-2022/maplebacoin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          resources:
            limits:
              cpu: "750m"
              memory: "512Mi"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maplebacoin
  namespace: challenges
spec:
  rules:
    - host: maplebacoin.ctf.maplebacon.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maplebacoin
                port:
                  number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: maplebacoin
  namespace: challenges
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: maplebacoin
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
