---
apiVersion: v1
kind: Service
metadata:
  name: puzzling-oversight
  namespace: challenges
  annotations:
    cloud.google.com/backend-config: '{"default": "release-wave-2"}'
    external-dns.alpha.kubernetes.io/hostname: "puzzling-oversight.ctf.maplebacon.org"
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: leet
      port: 1337
      targetPort: 1337
      protocol: TCP
  selector:
    app: puzzling-oversight
  sessionAffinity: ClientIP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puzzling-oversight
  labels:
    app: puzzling-oversight
  namespace: challenges
spec:
  selector:
    matchLabels:
      app: puzzling-oversight
  replicas: 2
  template:
    metadata:
      labels:
        app: puzzling-oversight
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: In
                    values:
                      - maplectf-node-pool
      enableServiceLinks: false
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: puzzling-oversight
          image: gcr.io/maplectf-2022/puzzling-oversight:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
              name: leet
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          tty: true
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: puzzling-oversight
  namespace: challenges
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: puzzling-oversight
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
