---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vienelibrary-deployment-restart
  namespace: challenges
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vienelibrary-deployment-restart
  namespace: challenges
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["vienelibrary"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vienelibrary-deployment-restart
  namespace: challenges
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vienelibrary-deployment-restart
subjects:
  - kind: ServiceAccount
    name: vienelibrary-deployment-restart
    namespace: challenges
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vienelibrary-deployment-restart
  namespace: challenges
spec:
  concurrencyPolicy: Forbid
  schedule: '*/4 * * * *'
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 240
      template:
        metadata:
          labels:
            deployment/restart: "vienelibrary"
        spec:
          serviceAccountName: vienelibrary-deployment-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - bash
                - -c
                - >-
                  kubectl rollout restart deployment/vienelibrary &&
                  kubectl rollout status deployment/vienelibrary
