# This is a basic workflow to help you get started with Actions

name: Update fluentd

# Controls when the workflow will run
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Allows one build at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-fluentd:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker images
        uses: docker/build-push-action@v3.1.0
        if: github.event_name == 'pull_request'
        with:
          context: ./2022int/fluentd/
          tags: bensonyanger/fluentd:latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          context: ./2022int/fluentd/
          push: true
          tags: bensonyanger/fluentd:latest
